name: dartea
description: A simple engine to run Model-View-Update (or TEA) apps in Flutter.
version: 0.0.2
author: p69 <shilyagov.p@gmail.com>
homepage: https://github.com/p69/dartea


environment:
  sdk: ">=1.23.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false