name: dartea
description: A simple engine to run Model-View-Update (or TEA) apps in Flutter.
version: 0.5.2
author: p69 <shilyagov.p@gmail.com>
homepage: https://github.com/p69/dartea


environment:
  sdk: ">=1.20.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: "^2.0.7"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false